version: '3.8'

services:
  postgres:
    image: postgres:15
    platform: linux/amd64
    container_name: dataulinzi_postgres
    environment:
      POSTGRES_DB: dataulinzi_db
      POSTGRES_USER: dataulinzi_user
      POSTGRES_PASSWORD: dataulinzi_secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dataulinzi_user -d dataulinzi_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: dataulinzi_redis
    command: redis-server --requirepass dataulinzi_redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: dataulinzi_redis_commander
    environment:
      REDIS_HOSTS: "local:redis:6379:0:dataulinzi_redis_password"
      HTTP_USER: admin
      HTTP_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      - redis
    profiles:
      - tools

  # Optional: pgAdmin for PostgreSQL management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dataulinzi_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dataulinzi.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    profiles:
      - tools

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local